. /usr/local/bin/color.sh

PORCENTAGE_0="${RED}* 0%${RESET}"
PORCENTAGE_10="${RED}** 10%${RESET}"
PORCENTAGE_15="${RED}*** 15%${RESET}"
PORCENTAGE_20="${RED}**** 20%${RESET}"
PORCENTAGE_25="${RED}***** 25%${RESET}"
PORCENTAGE_30="${RED}****** 30%${RESET}"
PORCENTAGE_35="${RED}******* 35%${RESET}"
PORCENTAGE_40="${CYAN}******** 40%${RESET}"
PORCENTAGE_45="${CYAN}********* 45%${RESET}"
PORCENTAGE_50="${CYAN}********** 50%${RESET}"
PORCENTAGE_55="${CYAN}*********** 55%${RESET}"
PORCENTAGE_60="${CYAN}************ 60%${RESET}"
PORCENTAGE_65="${CYAN}************* 65%${RESET}"
PORCENTAGE_70="${CYAN}*************** 70%${RESET}"
PORCENTAGE_75="${PURPLE}**************** 75%${RESET}"
PORCENTAGE_80="${PURPLE}***************** 80%${RESET}"
PORCENTAGE_85="${PURPLE}****************** 85% ${RESET}"
PORCENTAGE_90="${PURPLE}******************** 90%${RESET}"
PORCENTAGE_95="${PURPLE}********************* 95%${RESET}"
PORCENTAGE_100="${GREEN}************************ 100%${RESET}"